### ISSUE TITLE
The bot does not send version update PRs 

### ISSUE THREAD

**Issue by leofang** [conda-forge/rmm-feedstock#19]
We've released librmm 22.10 & 22.12 earlier, but the bot still has not sent PRs to this feedstock. 

cc: @conda-forge/librmm

**Comment by jakirkham** [comment]
The bot is [encountering an error due to `librmm` not always being up-to-date]( https://github.com/regro/autotick-bot/actions/runs/4113843237/jobs/7100466827#step:9:2203 ).

We could have the bot check whether `librmm` is out first before trying to update `rmm` [like what is done with `dask`]( https://github.com/conda-forge/dask-feedstock/blob/19cb78499e38b63a6f5cd2314a1aa0d93b3664ec/conda-forge.yml#L2 ). More details [about `check_solvable` in the docs]( https://conda-forge.org/docs/maintainer/conda_forge_yml.html#bot ).

Edit: Actually it looks like we have that [here]( https://github.com/conda-forge/rmm-feedstock/blob/4acdfd8f7ae41e65941e92d51c18caca95dc23a3/conda-forge.yml#L1-L2 ). Would suggest raising [a new bot issue]( https://github.com/regro/cf-scripts/issues/new ) and xref this issue there

**Comment by jakirkham** [comment]
Filed upstream issue ( https://github.com/regro/cf-scripts/issues/1601 )

**Comment by jakirkham** [comment]
Sounds like it was just waiting due to `librmm` version updates that were needed

AFAICT the bot is working now ( https://github.com/conda-forge/rmm-feedstock/pull/20 )

Going to close this (and the upstream issue)
